on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build
      - uses: actions/upload-artifact@v2
        with:
          name: OSDManual.html
          path: OSDManual.html
      - uses: actions/upload-artifact@v2
        with:
          name: OSDManual.pdf
          path: OSDManual.pdf
